apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
  host: mysql
  name: test

---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
  password: YWRtaW4xMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  username: dGVzdHVzZXI=
  password: dGVzdHVzZXJAMTIz
